
name: AKS via Terraform + 3-tier Guestbook

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'k8s/**'
      - '.github/workflows/aks-terraform.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show subscription
        run: az account show -o table

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Get Subscription ID
        id: sub
        run: echo "SUB_ID=$(az account show --query id -o tsv)" >> $GITHUB_OUTPUT

      - name: Terraform Plan
        env:
          TF_VAR_subscription_id: ${{ steps.sub.outputs.SUB_ID }}
          TF_VAR_vm_size: Standard_B4s_v2
        run: terraform -chdir=terraform plan -out=tfplan.bin


      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_subscription_id: ${{ steps.sub.outputs.SUB_ID }}
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tf
        working-directory: terraform
        run: |
          echo "RG=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
          echo "AKS=$(terraform output -raw aks_name)" >> $GITHUB_OUTPUT

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Helm version
        run: helm version
        

      - name: Deploy Guestbook App
        run: |
          kubectl apply -f k8s/guestbook/

      - name: Wait for frontend
        run: kubectl rollout status deploy/frontend -n guestbook --timeout=300s

      - name: Get frontend external IP
        run: kubectl get svc frontend -n guestbook -o wide
